server:
  port: 9999
spring:
  application:
    name: KUANGGOU-PRODUCT
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///kuanggou-product?serverTimezone=GMT%2B8
    username: root
    password: 199678

mybatis-plus:
  mapper-locations: classpath*:cn/itsource/kuanggou/mapper/*Mapper.xml



