server:
  port: 9527

spring:
  application:
    name: KUANGGOU-ZUUL

zuul:
  ignoredServices: '*' #只能通过路由访问，不能使用服务名访问
  routes:
    plat:
      serviceId: KUANGGOU-PLAT
      path: /plat/**
    product:
      serviceId: KUANGGOU-PRODUCT
      path: /product/**
    common: #添加common公共服务的路由
      serviceId: KUANGGOU-COMMON
      path: /common/**
  prefix: /services
#设置zuul超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  ConnectTimeout: 20000
  ReadTimeout: 20000