server:
  port: 9527

spring:
  application:
    name: KUANGGOU-ZUUL

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka/

zuul:
  ignoredServices: '*' #只能通过路由访问，不能使用服务名访问
  routes:
    plat:
      serviceId: KUANGGOU-PLAT
      path: /plat/**
  prefix: /services